config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :usuarios
  get 'welcome/index'
  get 'anuncios/emprestimos', to: 'anuncios#emprestimos'
  get 'anuncios/solicitacoes', to: 'anuncios#solicitacoes'
  resources :anuncios do
    resources :comments
    member do
      delete :delete_image_attachment
    end
  end
  root 'anuncios#index'
  resources :ratings
  get '/search', to: 'anuncios#search', as: 'search'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :nome, presence: true
  validates :snome, presence: true
  validates :fone, presence: true
  has_one_attached :avatar
  has_many :anuncios
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  wrap_parameters :usuario, include: [:nome, :snome, :email, :password, :password_confirmation, :fone]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Dados atualizados.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario foi excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome, :snome, :email, :password, :password_confirmation, :fone, :avatar)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> surgiram no cadastro:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label "Profile Photo" %>
  <%= form.file_field :avatar %> <br>


  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :snome %>
    <%= form.text_field :snome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :fone %>
    <%= form.text_field :fone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Atualizar dados</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Voltar', @usuario %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuários</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.snome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.fone %></td>
        <td><%= link_to 'Mostrar', usuario %></td>
        <td><%= link_to 'Modificar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Excluir', usuario, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo usuário', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Cadastre-se</h1>

<%= render 'form', usuario: @usuario %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @usuario.snome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.fone %>
</p>

<%= link_to 'Editar dados', edit_usuario_path(@usuario) %>

<br><br><br>

<h3> Itens ofertados para empréstimo </h3>
<table>
 <tr>
    <th>Item</th>
    <th>Descrição</th>
    <th>Horário</th>
    <th>Tags</th>
  </tr>
  
  <% @usuario.anuncios.each do |anuncio| %>
    <% if anuncio.tipo == 'emprestimo'%>
      <tr>
        <td><%= anuncio.item %></td>
        <td><%= anuncio.descrição %></td>
        <td><%= anuncio.horário %></td>
        <td><%= anuncio.tags %></td>
        
        <td><%= link_to 'Show', anuncio_path(anuncio) %></td>

        <% if current_user %>
          <% if anuncio.usuario_id == current_user.id %>
            <td><%= link_to 'Edit', edit_anuncio_path(anuncio) %></td>
            <td><%= link_to 'Destroy', anuncio_path(anuncio), method: :delete, data: { confirm: 'Tem certeza que deseja excluir o anuncio?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

<h3> Itens solicitados pelo usuário </h3>
<table>
 <tr>
    <th>Item</th>
    <th>Descrição</th>
    <th>Horário</th>
    <th>Tags</th>
  </tr>
  
  <% @usuario.anuncios.each do |anuncio| %>
    <% if anuncio.tipo == 'solicitacao'%>
      <tr>
        <td><%= anuncio.item %></td>
        <td><%= anuncio.descrição %></td>
        <td><%= anuncio.horário %></td>
        <td><%= anuncio.tags %></td>
        
        <td><%= link_to 'Show', anuncio_path(anuncio) %></td>

        <% if current_user %>
          <% if anuncio.usuario_id == current_user.id %>
            <td><%= link_to 'Edit', edit_anuncio_path(anuncio) %></td>
            <td><%= link_to 'Destroy', anuncio_path(anuncio), method: :delete, data: { confirm: 'Tem certeza que deseja excluir o anuncio?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>