config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :usuarios
  get 'welcome/index'
  get 'anuncios/emprestimos', to: 'anuncios#emprestimos'
  get 'anuncios/solicitacoes', to: 'anuncios#solicitacoes'
  resources :anuncios do
    resources :comments
    member do
      delete :delete_image_attachment
    end
  end
  root 'anuncios#index'
  resources :ratings
  get '/search', to: 'anuncios#search', as: 'search'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/anuncio.rb
class Anuncio < ApplicationRecord 
    has_many :comments
    belongs_to :usuario

    has_many_attached :imagens

    validates :item, presence: true
    validates :tipo, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :anuncio
  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :body, presence: :true
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { ChatBroadcastJob.perform_later self }
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
    validates :nome, presence: true
    validates :nota, numericality: { only_integer: true, greater_than_or_equal_to:0,
    less_than_or_equal_to:10 }
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :nome, presence: true
  validates :snome, presence: true
  validates :fone, presence: true
  has_one_attached :avatar
  has_many :anuncios
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController 
    helper_method :sort_column, :sort_direction       
    def index
        @anuncios = Anuncio.all
        @anuncios = Anuncio.order(sort_column + " " + sort_direction)
    end
    
    def show
        @anuncio = Anuncio.find(params[:id])
    end
    
    def new
    end
    
    def edit
        @anuncio = Anuncio.find(params[:id])
    end
    
    def create
        @anuncio = Anuncio.new(anuncio_params)
        @anuncio.usuario_id = current_user.id
        @anuncio.save
        redirect_to @anuncio
    end
    
    def update
        @anuncio = Anuncio.find(params[:id])

        if @anuncio.update(params[:anuncio].permit(:item, :descrição, :horário, :tags, :tipo))
            if params[:anuncio][:imagens].present?
                params[:anuncio][:imagens].each do |imagem|
                    @anuncio.imagens.attach(imagem)
                end
            end
            redirect_to @anuncio
        else
            render 'edit'
        end
    end

    def delete_image_attachment
        @imagem = ActiveStorage::Attachment.find(params[:id])
        @imagem.purge
        redirect_back(fallback_location: anuncios_path)
    end
    
    def destroy
        @anuncio = Anuncio.find(params[:id])
        
        @anuncio.destroy
        redirect_to anuncios_path
    end
    
    

    def anuncio_params
            params.require(:anuncio).permit(:item, :descrição, :horário, :tags, :tipo, imagens: [])
    end

    def search  
        if params[:search].blank?  
            redirect_to(root_path, alert: "Empty field!") and return  
        else  
            @parameter = params[:search].downcase  
            @results = Anuncio.all.where("lower(item) LIKE :search", search: "#{@parameter}%")
            @tags= Anuncio.all.where("lower(tags) LIKE :search", search: "#{@parameter}%")  
           
        end
    end

        def emprestimos
            @anuncios = Anuncio.all
            @anuncios_de_emprestimo = []
            @anuncios.each do |anuncio|
                @anuncios_de_emprestimo << anuncio if anuncio.tipo == 'emprestimo'
            end
        end

        def solicitacoes
            @anuncios = Anuncio.all
            @anuncios_de_solicitacao = []
            @anuncios.each do |anuncio|
                @anuncios_de_solicitacao << anuncio if anuncio.tipo == 'solicitacao'
                end
            end
        end
 
    private

    def sort_column
        Anuncio.column_names.include?(params[:sort]) ? params[:sort] : "item"
    end
      
    def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

    def show
        @messages = Message.all
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @anuncio = Anuncio.find(params[:anuncio_id])
        @comment = @anuncio.comments.create(params[:comment].permit(:name, :body))
        @comment.name = current_user.nome + ' ' + user.current_user.snome
        @comment.save
        redirect_to anuncio_path(@anuncio)
    end
    def new
        @anuncio = Anuncio.find(params[:anuncio_id])
        @comment = @anuncio.comments.new(parent_id: params[:parent_id])
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   
    def main
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id]) 
    end

    def new
    
    end

    def create
        #render plain: params[:posts].inspect
        @post = Post.new(post_params)
        @post.save
        redirect_to @post
    end
        
    private def post_params
        params.require(:post).permit(:Obj,:Notes,:time,:tags)
    end
        
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    def new 
        @rating= Rating.new
    end

    def index
        @rating = Rating.all
    end

    def edit 
        @rating = Rating.find(params[:id])
    end

    def update 
        @rating = Rating.find(params[:id])
        
        if @rating.update(rating_params)
            redirect_to @rating
        else
            render 'edit'
        end
    end

    def destroy 
        @rating = Rating.find(params[:id])
        @rating.destroy
       
        redirect_to ratings_path
    end        

    def create
        @rating = Rating.new(rating_params)
       
        if @rating.save
            redirect_to @rating
        else
            render 'new'
        end 
    end
    
    def show
        @rating = Rating.find(params[:id])
    end


    
private
    def rating_params
        params.require(:rating).permit(:nome, :nota)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    usuario = Usuario.find_by_email(params[:email])
    if usuario && usuario.authenticate(params[:password])
      session[:usuario_id] = usuario.id
      redirect_to root_url
    else
      flash.now[:alert] = "Email ou senha é inválida."
      render "new"
    end
  end
  def destroy
    session[:usuario_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}, {:class => css_class}
      end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/anuncios/edit.html.erb
<h1>Editar Anúncio</h1>
 
<%= form_with(model: @anuncio, local: true) do |form| %>
 
  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@anuncio.errors.count, "error") %> impediram esse Anúncio de ser salvo:
      </h2>
      <ul>
        <% @anuncio.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
 
  <p>
      <%= form.label :"item" %><br>
      <%= form.text_field :"item" %>
    </p>
   
    <p>
      <%= form.label :descrição %><br>
      <%= form.text_area :descrição %>
    </p>
   
    <p>
      <%= form.label :horário %><br>
      <%= form.text_field :horário %>
    </p>

    <p>
      <%= form.label :tags %><br>
      <%= form.text_field :tags %>
    </p>

    <p>
      <%= form.label :tipo %><br>
      <%= form.radio_button :tipo, 'emprestimo' %> Empréstimo<br />
      <%= form.radio_button :tipo, 'solicitacao' %> Solicitação<br />
    </p>

    <p>
      <%= form.label :imagens %><br>
      <%= form.file_field :imagens, multiple: true, :id => "imagem_anuncio_button" %>     
    </p>

    <% if @anuncio.imagens.attached? %>
      <% (0...@anuncio.imagens.count).each do |imagem| %>
        <div class="show_image_holder">
          <img src = "<%=(url_for(@anuncio.imagens[imagem]))%>", class = "show_imagem_anuncio">
          <%= link_to "Remove", delete_image_attachment_anuncio_url(@anuncio.imagens[imagem]), method: :delete, data: {confirm: "Tem certeza?"} %>
        </div>
      <% end %>
    <% end %>

    <p>
      <%= form.submit %>
    </p>
 
<% end %>
 
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/emprestimos.html.erb
          <%= form_tag(search_path, :method => "get",   
            class: 'navbar-form navbar-left') do %>  
          <div class="input-group">  
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
          <div class="input-group-btn">  
          <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
          </div>  
          </div>
          
          <% end %>
<h1>Objetos para pegar emprestado</h1>

  <table>
  <tr>
    <th>Imagem</th>
    <th>Item</th>
    <th>Descrição</th>
    <th>Horário</th>
    <th>Tags</th>
    <th>Usuário</th>
  </tr>

  <% @anuncios_de_emprestimo.each do |anuncio| %>
    <tr>
      <% if anuncio.imagens.attached? %>
        <td><img src = "<%=(url_for(anuncio.imagens.first))%>", class="index_imagem_anuncio"></td>
      <% else %>
        <%= %>
        <td><img src = "<%=(image_url('anunciosemimagem.jpeg'))%>", class="index_imagem_anuncio"></td>
      <% end %>

      <td><%= anuncio.item %></td>
      <td><%= anuncio.descrição %></td>
      <td><%= anuncio.horário %></td>
      <td><%= anuncio.tags %></td>
      <td><%= anuncio.usuario.nome %> <%= anuncio.usuario.snome %></td>
      
      <td><%= link_to 'Show', anuncio_path(anuncio) %></td>

      <% if current_user %>
        <% if anuncio.usuario_id == current_user.id %>
          <td><%= link_to 'Edit', edit_anuncio_path(anuncio) %></td>
          <td><%= link_to 'Destroy', anuncio_path(anuncio), method: :delete, data: { confirm: 'Tem certeza que deseja excluir o anuncio?' } %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>

<% if current_user %>
<%=link_to "add", new_anuncio_path, :class => "material-icons floating-btn" %>
<% end %>

app/views/anuncios/index.html.erb
          <%= form_tag(search_path, :method => "get",   
            class: 'navbar-form navbar-left') do %>  
          <div class="input-group">  
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
          <div class="input-group-btn">  
          <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
          </div>  
          </div>
          
          <% end %>
<h1>Objetos</h1>


  <table>
  <tr>
    <th>Imagem</th>
    <th><%= sortable "item", "Item" %></th>
    <th><%= sortable "descrição", "Descrição"  %></th>
    <th><%= sortable "horário", "Horário"  %></th>
    <th><%= sortable "tags", "Tags"  %></th>
    <th><%= sortable "usuário", "Usuário"  %></th>
    <th><%= sortable "tipo", "Tipo" %></th>
  </tr>

  <% @anuncios.each do |anuncio| %>
    <tr>
      <% if anuncio.imagens.attached? %>
        <td><img src = "<%=(url_for(anuncio.imagens.first))%>", class="index_imagem_anuncio"></td>
      <% else %>
        <%= %>
        <td><img src = "<%=(image_url('anunciosemimagem.jpeg'))%>", class="index_imagem_anuncio"></td>
      <% end %>

      <td><%= anuncio.item %></td>
      <td><%= anuncio.descrição %></td>
      <td><%= anuncio.horário %></td>
      <td><%= anuncio.tags %></td>
      <td><%= anuncio.usuario.nome %> <%= anuncio.usuario.snome %></td>
      <td><%= anuncio.tipo %></td>
      
      <td><%= link_to 'Show', anuncio_path(anuncio) %></td>

      <% if current_user %>
        <% if anuncio.usuario_id == current_user.id %>
          <td><%= link_to 'Edit', edit_anuncio_path(anuncio) %></td>
          <td><%= link_to 'Destroy', anuncio_path(anuncio), method: :delete, data: { confirm: 'Tem certeza que deseja excluir o anuncio?' } %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>

<% if current_user %>
<%=link_to "add", new_anuncio_path, :class => "material-icons floating-btn" %>
<% end %>

app/views/anuncios/new.html.erb
<%= form_with scope: :anuncio, url: anuncios_path, local: true do |form| %>
    <p>
      <%= form.label :"item" %><br>
      <%= form.text_field :"item" %>
    </p>
   
    <p>
      <%= form.label :descrição %><br>
      <%= form.text_area :descrição %>
    </p>
   
    <p>
      <%= form.label :horário %><br>
      <%= form.text_field :horário %>
    </p>

    <p>
      <%= form.label :tags %><br>
      <%= form.text_field :tags %>
    </p>

    <p>
      <%= form.label :tipo %><br>
      <%= form.radio_button :tipo, 'emprestimo' %> Empréstimo<br />
      <%= form.radio_button :tipo, 'solicitacao' %> Solicitação<br />
    </p>

    <p>
      <%= form.label :imagens %><br>
      <%= form.file_field :imagens, multiple: true, :id => "imagem_anuncio_button" %>      
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/anuncios/search.html.erb
<h3>Resultados da busca</h3>  

<h4> Itens relacionados</h4>
  <table>
  <tr>
    <th>item</th>
    <th>descrição</th>
    <th>horário</th>
    <th>tags</th>
  </tr>

  <% @results.each do |result| %>  
    <tr>
     <td><%=  result.item %></td>
      <td><%= result.descrição %></td>
      <td><%= result.horário %></td>
      <td><%= result.tags %></td>
    </tr>
    <% end %>
</table>

<h4> Tags relacionadas</h4>

<table>
  <tr>
    <th>item</th>
    <th>descrição</th>
    <th>horário</th>
    <th>tags</th>
  </tr>

  <% @tags.each do |tag| %>  
    <tr>
     <td><%=  tag.item %></td>
      <td><%= tag.descrição %></td>
      <td><%= tag.horário %></td>
      <td><%= tag.tags %></td>
    </tr>
    <% end %>
</table>

app/views/anuncios/show.html.erb
<h3> Item de <%= @anuncio.tipo %></h3>

<% if @anuncio.imagens.attached? %>
  <% (0...@anuncio.imagens.count).each do |imagem| %>
    <div class="show_image_holder">
      <img src = "<%=(url_for(@anuncio.imagens[imagem]))%>", class = "show_imagem_anuncio">
    </div>
  <% end %>
<% else %>
  <div style="width: 200px; height: 200px;">
    <img src = "<%=(image_url('anunciosemimagem.jpeg'))%>", class = "show_imagem_anuncio">
  </div>
<% end %>

<p>
  <strong>Item:</strong>
  <%= @anuncio.item %>
</p>
 
<p>
  <strong>Descrição:</strong>
  <%= @anuncio.descrição %>
</p>

<p>
  <strong>Horário:</strong>
  <%= @anuncio.horário %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @anuncio.tags %>
</p>

<br><strong>Entre em contato - Usuário</strong>
<p>
  <% if @anuncio.usuario.avatar.attached? %>
    <img src = "<%=(url_for(@anuncio.usuario.avatar))%>", class = "pfp">
  <% else %>
    <%= image_tag image_url('default_pfp.jpg'), :class => "pfp" %>
  <% end %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @anuncio.usuario.nome %> <%= @anuncio.usuario.snome %>
</p>
<p>
  <strong>Email:</strong>
  <%= @anuncio.usuario.email %>
</p>

<br>
<h2><%= @anuncio.comments.count%> Comentários</h2>


<%= render @anuncio.comments %>

<h3>Adicionar um comentário</h3>
<%= render 'comments/form' %>
<br>


<%= link_to 'Back', anuncios_path %>

<% if current_user %>
  <% if @anuncio.usuario_id == current_user.id?%>
    <%= link_to 'Edit', edit_anuncio_path(@anuncio) %>
  <% end %>
<% end %>

app/views/anuncios/solicitacoes.html.erb
          <%= form_tag(search_path, :method => "get",   
            class: 'navbar-form navbar-left') do %>  
          <div class="input-group">  
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
          <div class="input-group-btn">  
          <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
          </div>  
          </div>
          
          <% end %>
<h1>Objetos solicitados</h1>

  <table>
  <tr>
    <th>Imagem</th>
    <th>Item</th>
    <th>Descrição</th>
    <th>Horário</th>
    <th>Tags</th>
    <th>Usuário</th>
  </tr>

  <% @anuncios_de_solicitacao.each do |anuncio| %>
    <tr>
      <% if anuncio.imagens.attached? %>
        <td><img src = "<%=(url_for(anuncio.imagens.first))%>", class="index_imagem_anuncio"></td>
      <% else %>
        <%= %>
        <td><img src = "<%=(image_url('anunciosemimagem.jpeg'))%>", class="index_imagem_anuncio"></td>
      <% end %>

      <td><%= anuncio.item %></td>
      <td><%= anuncio.descrição %></td>
      <td><%= anuncio.horário %></td>
      <td><%= anuncio.tags %></td>
      <td><%= anuncio.usuario.nome %> <%= anuncio.usuario.snome %></td>
      
      <td><%= link_to 'Show', anuncio_path(anuncio) %></td>

      <% if current_user %>
        <% if anuncio.usuario_id == current_user.id %>
          <td><%= link_to 'Edit', edit_anuncio_path(anuncio) %></td>
          <td><%= link_to 'Destroy', anuncio_path(anuncio), method: :delete, data: { confirm: 'Tem certeza que deseja excluir o anuncio?' } %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>

<% if current_user %>
<%=link_to "add", new_anuncio_path, :class => "material-icons floating-btn" %>
<% end %>

app/views/comments/_comment.html.erb
<h4><%= comment.name %></h4>
<p><%= comment.body %></p>
<p><%= time_ago_in_words(comment.created_at) %></p>

<%= link_to 'responder', new_anuncio_comment_path(@anuncio, parent_id: comment.id), remote: true %>
<div>
    <% comment.replies.each do |reply| %> 
      <%= render partial: 'comments/reply', locals: { reply: reply } %>
    <% end %>
</div>
 
 <div id="reply-form-<%= comment.id %>"></div>

app/views/comments/_form.html.erb
<%= form_for([@anuncio, @anuncio.comments.build]) do |f|%>

<p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
</p>
<br>
<p>
    <%= f.submit %>
</p>

<% end %>


app/views/comments/_reply.html.erb
<div >
  <div >
    <%= reply.body %>
  </div>
</div>

app/views/comments/_reply_form.html.erb
<div >
  <div >
    <%= form_with(model: [@anuncio, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div >
        <%= f.label 'Reply' %>
        <%= f.text_area :body %>
      </div>
      <%= f.submit 'Submit' %>
      <%= link_to 'Cancel', anuncio_path(@anuncio) %>
    <% end %>
  </div>
</div>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/posts/main.html.erb
<h1>Objetos para pegar emprestado</h1>

<% @posts.each do |post| %>

<h2><%= post.Obj %></h2>
<h3>Descrição:</h3>
<p><%= post.Notes %></p>
<h3>Horário Disponível:</h3>
<p><%= post.time %></p>
<h3> Tags: </h3>
<p><%= post.tags %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Divulgar um Objeto </h1>

<%= form_for :post, url: posts_path do |f| %>
<p>
<%= f.label :Obj %><br>
<%= f.text_field :Obj %>
</p>

<p>
<%= f.label :Notes %><br>
<%= f.text_area :Notes %> 
</p>

<p>
<%= f.label :time %><br>
<%= f.text_field :time %>
</p>

<p>
<%= f.label :tags %><br>
<%= f.text_area :tags %> 
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/posts/show.html.erb

<h2><%= @post.Obj %>
<p><%= @post.Notes %></p>
<p><%= @post.time %></p>
<p><%= @post.tags %></p>

app/views/ratings/edit.html.erb
<h1>De uma nova avaliação</h1>

<%= form_with scope: :rating, url: ratings_path, local: true do |form| %>
    <%if @rating.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rating.errors.count, "erros") %>
        não deixaram que esta avaliação fosse salva
      </h2>
      <ul>
        <% @rating.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <p>
  <%= form.label :nome %><br>
  <%= form.text_field :nome %>
    </p>
    <p>
      <%= form.label :nota %><br>
      <%= form.text_field :nota %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>
   

app/views/ratings/index.html.erb
<h1>Avaliações</h1>
<table>
    <tr>
    <th>Nome</th>
    <th>Nota</th>
    </tr>
    <% @rating.each do |rating| %>
    <tr>
        <td><%= rating.nome %></td>
        <td><%= rating.nota %></td>
        <td><%= link_to 'Mostrar', rating_path(rating) %></td>
        <td><%= link_to 'Editar', edit_rating_path(rating) %></td>
        <td><%= link_to 'Deletar', rating_path(rating),
            method: :delete,
                data: { confirm: 'Você tem certeza?' } %></td>
    </tr>
    <% end %>
</table>

app/views/ratings/new.html.erb
<%= form_with scope: :rating, url: ratings_path, local: true do |form| %>
  <%if @rating.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@rating.errors.count, "erros") %>
      não deixaram que esta avaliação fosse salva
    </h2>
    <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

 
  <p>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
  </p>
 
  <p>
    <%= form.label :nota %><br>
    <%= form.text_field :nota %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 

app/views/ratings/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @rating.nome %>
</p>
 
<p>
  <strong>Nota:</strong>
  <%= @rating.nota %>
</p>