config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :usuarios
  get 'welcome/index'
  get 'anuncios/emprestimos', to: 'anuncios#emprestimos'
  get 'anuncios/solicitacoes', to: 'anuncios#solicitacoes'
  resources :anuncios do
    resources :comments
    member do
      delete :delete_image_attachment
    end
  end
  root 'anuncios#index'
  resources :ratings
  get '/search', to: 'anuncios#search', as: 'search'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/anuncio.rb
class Anuncio < ApplicationRecord 
    has_many :comments
    belongs_to :usuario

    has_many_attached :imagens

    validates :item, presence: true
    validates :tipo, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :anuncio
  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :body, presence: :true
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { ChatBroadcastJob.perform_later self }
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
    validates :nome, presence: true
    validates :nota, numericality: { only_integer: true, greater_than_or_equal_to:0,
    less_than_or_equal_to:10 }
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :nome, presence: true
  validates :snome, presence: true
  validates :fone, presence: true
  has_one_attached :avatar
  has_many :anuncios
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

    def show
        @messages = Message.all
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   
    def main
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id]) 
    end

    def new
    
    end

    def create
        #render plain: params[:posts].inspect
        @post = Post.new(post_params)
        @post.save
        redirect_to @post
    end
        
    private def post_params
        params.require(:post).permit(:Obj,:Notes,:time,:tags)
    end
        
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    def new 
        @rating= Rating.new
    end

    def index
        @rating = Rating.all
    end

    def edit 
        @rating = Rating.find(params[:id])
    end

    def update 
        @rating = Rating.find(params[:id])
        
        if @rating.update(rating_params)
            redirect_to @rating
        else
            render 'edit'
        end
    end

    def destroy 
        @rating = Rating.find(params[:id])
        @rating.destroy
       
        redirect_to ratings_path
    end        

    def create
        @rating = Rating.new(rating_params)
       
        if @rating.save
            redirect_to @rating
        else
            render 'new'
        end 
    end
    
    def show
        @rating = Rating.find(params[:id])
    end


    
private
    def rating_params
        params.require(:rating).permit(:nome, :nota)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}, {:class => css_class}
      end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P2P EACH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>

  <body>
    <ul class="navbar-list">
      <div id="navbar_title">
        <li><%=link_to "P2P EACH", anuncios_path, :class => "navbar-list-link" %></li>
      </div>
      <% if current_user %>
        <li><%= link_to current_user, :class => "navbar-list-link perfil" do%>
          <% if current_user.avatar.attached? %>
            <img src = "<%=(url_for(current_user.avatar))%>", class = "pfp">
          <% else %>
            <%= image_tag image_url('default_pfp.jpg'), :class => "pfp" %>
          <% end %>
          <%= "#{current_user.nome} #{current_user.snome}"%>
        <% end %></li>
        <li><%= link_to "LOGOUT", logout_path, :class => "navbar-list-link" %></li>
      <% else %>
        <li><%=link_to "CADASTRE-SE", signup_path, :class => "navbar-list-link" %></li>
        <li><%=link_to "LOGIN", login_path, :class => "navbar-list-link" %></li>
      <% end %>
        <li><%= link_to "AVALIAÇÕES ", ratings_path,:class => "navbar-list-link" %> </li>
    </ul>
    <%= yield %>
</body>
</html>